include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.swagger.dart"

  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - public_member_api_docs

dart_code_metrics:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.swagger.dart"
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
