name: dart_brompton
description: A library for controlling Brompton systems over a network
version: 2.1.0
repository: https://github.com/point-source/dart_brompton

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  chopper: ^5.1.0
  collection: ^1.17.0
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.2.0
  chopper_generator: ^5.1.0+1
  json_serializable: ^6.3.1
  lints: ^2.0.0
  swagger_dart_code_generator: ^2.7.6+1
  test: ^1.16.0

dependency_overrides:
  swagger_dart_code_generator:
    git:
      url: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator
