name: dart_brompton
description: A library for controlling Brompton Tessera systems over a network
version: 4.0.0
repository: https://github.com/point-source/dart_brompton

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  chopper: ^7.0.9
  collection: ^1.17.0
  http: ^1.1.2
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.2.0
  chopper_generator: ^7.0.6
  json_serializable: ^6.3.1
  lints: ^3.0.0
  swagger_dart_code_generator: ^2.8.9
  test: ^1.16.0
